#!/bin/bash
#
# Point to the pipeline
#
ROOT=/usr/local/share/pipelines/nlpp
BIND=$ROOT/bin
#
# The naf to be processed
#
INFIL=$1
#
# This demo stores the result of every process-step. You can modify this of course.
#
FILTRUNK=$INFIL

#TOKFIL=$FILTRUNK.tok.naf
MORFIL=$FILTRUNK
NERCFIL=$FILTRUNK.nerc
#WSDFIL=$FILTRUNK.wsd
NEDFIL=$FILTRUNK.nerc.ned.naf
#ONTOFIL=$FILTRUNK.onto.naf
#TIMESFIL=$FILTRUNK.times.naf
#SRLFIL=$FILTRUNK.srl.naf
#ECRFFIL=$FILTRUNK.ecrf.naf
#OUTFIL=$FILTRUNK.out.naf

#echo text to naf
#gawk -f ./txt2naf.awk $INTEXT   > $OUTFIL
#echo Tokenize:
#cat $INFIL   | $BIND/tok        > $TOKFIL
#echo Morph:
#cat $TOKFIL  | $BIND/mor        > $MORFIL
echo NERC:
cat $MORFIL  | $BIND/nerc       > $NERCFIL 2> /dev/null
#echo wsd:
#cat $NERCFIL | $BIND/wsd        > $WSDFIL   
echo NED:
cat $NERCFIL  | $BIND/ned        > $NEDFIL 2> /dev/null   
#echo  Onto:
#cat $NEDFIL  | $BIND/onto       > $ONTOFIL  
#echo Heideltime:
#cat $ONTOFIL | $BIND/heideltime > $TIMESFIL 
#echo SRL:
#cat $TIMESFIL| $BIND/srl        > $SRLFIL   
#echo Evcoref:
#cat $SRLFIL  | $BIND/evcoref    > $ECRFFIL  
#echo framesrl:
#cat $ECRFFIL | $BIND/framesrl    > $OUTFIL   

